 scanner:
    image: deffmsecdeploy01.emea.tpg.ads:5000/tenable/nessus:1.0.2
    stdin_open: true
    volumes:
    - nessus_etc:/opt/nessus/etc
    - nessus_lib:/opt/nessus/lib
    - nessus_var:/opt/nessus/var
    tty: true
    ports:
    - ${port}:8834/tcp
    command:
    - /opt/nessus/sbin/nessusd
    labels:
      io.rancher.container.pull_image: always